# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GregorKrebs.NeoSSHWinManager
PackageVersion: 1.7.0
InstallerLocale: en-US
InstallerType: inno
UpgradeBehavior: install
ReleaseDate: 2026-10-09
Dependencies:
  PackageDependencies:
  - PackageIdentifier: WinFsp.WinFsp
  - PackageIdentifier: SSHFS-Win.SSHFS-Win
ProductCode: '{B4E6F1A2-7C3D-4E5A-9F8B-1D2C3E4F5A6B}_is1'
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/gregorkrebs/NeoSSHWinManager/releases/download/v1.7.0/NeoSSHWinManager-Setup-1.7.0.exe
  InstallerSha256: 108FBAE70D9B6996598966060CB101D6BF4790A07746C45D3EE5BD3E5E43870E
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/gregorkrebs/NeoSSHWinManager/releases/download/v1.7.0/NeoSSHWinManager-Setup-1.7.0.exe
  InstallerSha256: 108FBAE70D9B6996598966060CB101D6BF4790A07746C45D3EE5BD3E5E43870E
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
