# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GregorKrebs.NeoSSHWinManager
PackageVersion: 1.7.2
InstallerLocale: en-US
InstallerType: inno
UpgradeBehavior: install
ReleaseDate: 2026-10-09
Dependencies:
  PackageDependencies:
  - PackageIdentifier: WinFsp.WinFsp
  - PackageIdentifier: SSHFS-Win.SSHFS-Win
ProductCode: '{B4E6F1A2-7C3D-4E5A-9F8B-1D2C3E4F5A6B}_is1'
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/gregorkrebs/NeoSSHWinManager/releases/download/v1.7.2/NeoSSHWinManager-Setup-1.7.2.exe
  InstallerSha256: B0FCC397046139B991125DEFE04EADE7A13094A063454741DE4E9ACD54D68A5C
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/gregorkrebs/NeoSSHWinManager/releases/download/v1.7.2/NeoSSHWinManager-Setup-1.7.2.exe
  InstallerSha256: B0FCC397046139B991125DEFE04EADE7A13094A063454741DE4E9ACD54D68A5C
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
